# Generated by Django 3.0.4 on 2020-06-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, choices=[(1, '10代'), (2, '20代'), (3, '30代'), (4, '40代'), (5, '50代'), (6, '60代'), (7, '70代'), (8, '80代以降')], null=True, verbose_name='年齢'),
        ),
    ]
