# Generated by Django 3.0.6 on 2020-07-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlog',
            options={'verbose_name': 'ユーザーログ', 'verbose_name_plural': 'ユーザーログ'},
        ),
    ]
