# Generated by Django 2.2.4 on 2020-07-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlog',
            options={'verbose_name': 'ログ', 'verbose_name_plural': 'ログ'},
        ),
    ]
