# Generated by Django 3.0.6 on 2020-07-02 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200701_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='purchase_time',
            field=models.DurationField(blank=True, null=True, verbose_name='所要時間'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='タイムスタンプ'),
        ),
    ]
