# Generated by Django 3.0.7 on 2020-07-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20200702_1544'),
        ('users', '0005_merge_20200702_1429'),
    ]

    operations = [
    ]
