# Generated by Django 3.0.6 on 2020-06-13 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='F_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('quontity', models.IntegerField(blank=True, null=True, verbose_name='何kg出そうか')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='いつ出そうか')),
                ('vegetable', models.IntegerField(blank=True, choices=[(1, '人参'), (2, '大根'), (3, 'じゃがいも'), (4, 'キャベツ'), (5, 'ホウレンソウ'), (6, 'ピーマン'), (7, 'なにかしら')], null=True, verbose_name='出せる野菜')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='作成時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='更新時間')),
                ('I_name', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='出品者')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='F_CreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='F_UpdatedBy', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'サンプル',
                'verbose_name_plural': 'サンプル',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='作成時間')),
                ('quontity', models.IntegerField(blank=True, null=True, verbose_name='予約数量')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('subscriber', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Subscriber', to=settings.AUTH_USER_MODEL, verbose_name='予約者')),
                ('target', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='F_Item', to='app.F_Item', verbose_name='商品アイテム')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='施設名')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('quontity', models.IntegerField(blank=True, null=True, verbose_name='何kgほしいか')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='いつほしいか')),
                ('vegetable', models.IntegerField(blank=True, choices=[(1, '人参'), (2, '大根'), (3, 'じゃがいも'), (4, 'キャベツ'), (5, 'ホウレンソウ'), (6, 'ピーマン'), (7, 'なんでもいい')], null=True, verbose_name='ほしい野菜')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='作成時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='更新時間')),
                ('I_name', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='入力者氏名')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='C_CreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='C_UpdatedBy', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'サンプル',
                'verbose_name_plural': 'サンプル',
            },
        ),
    ]
