# Generated by Django 3.0.6 on 2020-06-27 09:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='F_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25, null=True, verbose_name='商品名')),
                ('unit_amount', models.CharField(max_length=10, verbose_name='１セット内容量')),
                ('rank', models.IntegerField(choices=[(1, 'Aランク（販売用良品)'), (2, 'Bランク（販売用訳あり品）'), (3, 'Cランク（販売不適可品）'), (4, 'Dランク（非食用品）')], verbose_name='ランク')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('quontity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, '1セット以上の出品をしてください')], verbose_name='出品セット数')),
                ('quontity_left', models.PositiveIntegerField(blank=True, null=True, verbose_name='在庫')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='セット単価（￥）')),
                ('deadline', models.DateField(blank=True, default=datetime.datetime(2020, 7, 4, 18, 18, 3, 766917), null=True, verbose_name='購入期限')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='f_items/', verbose_name='写真（任意）')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='出品時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='施設名')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('quontity', models.IntegerField(blank=True, null=True, verbose_name='何kgほしいか')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='いつほしいか')),
                ('vegetable', models.IntegerField(blank=True, choices=[(1, '人参'), (2, '大根'), (3, 'じゃがいも'), (4, 'キャベツ'), (5, 'ホウレンソウ'), (6, 'ピーマン'), (7, 'なんでもいい')], null=True, verbose_name='ほしい野菜')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='作成時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '需要',
                'verbose_name_plural': '需要',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成時間')),
                ('total_price', models.PositiveIntegerField(blank=True, verbose_name='合計金額')),
                ('quontity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, '1セット以上の購入をしてください')], verbose_name='購入セット数')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備考')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '訳あり理由',
                'verbose_name_plural': '訳あり理由',
            },
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '取り扱い野菜',
                'verbose_name_plural': '取り扱い野菜',
            },
        ),
    ]
