# Generated by Django 3.0.6 on 2020-06-26 14:16

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='F_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='商品名')),
                ('unit_amount', models.CharField(max_length=10, verbose_name='１セット内容量')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('quontity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, '1セット以上の出品をしてください')], verbose_name='出品セット数')),
                ('quontity_left', models.PositiveIntegerField(blank=True, null=True, verbose_name='在庫')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='セット単価（￥）')),
                ('deadline', models.DateField(blank=True, default=datetime.datetime(2020, 7, 3, 23, 16, 37, 509193), null=True, verbose_name='購入期限')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='f_items/', verbose_name='写真（任意）')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='出品時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='更新時間')),
                ('I_name', models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.PROTECT, related_name='F_exhibitor', to=settings.AUTH_USER_MODEL, verbose_name='出品者')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='F_CreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='出品者')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '訳あり理由',
                'verbose_name_plural': '訳あり理由',
            },
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '取り扱い野菜',
                'verbose_name_plural': '取り扱い野菜',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成時間')),
                ('total_price', models.PositiveIntegerField(blank=True, verbose_name='合計金額')),
                ('quontity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, '1セット以上の購入をしてください')], verbose_name='購入セット数')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('subscriber', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='Subscriber', to=settings.AUTH_USER_MODEL, verbose_name='購入者')),
                ('target', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='F_Item', to='app.F_Item', verbose_name='商品アイテム')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='施設名')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('quontity', models.IntegerField(blank=True, null=True, verbose_name='何kgほしいか')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='いつほしいか')),
                ('vegetable', models.IntegerField(blank=True, choices=[(1, '人参'), (2, '大根'), (3, 'じゃがいも'), (4, 'キャベツ'), (5, 'ホウレンソウ'), (6, 'ピーマン'), (7, 'なんでもいい')], null=True, verbose_name='ほしい野菜')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='作成時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='更新時間')),
                ('I_name', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='入力者氏名')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='C_CreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='C_UpdatedBy', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '需要',
                'verbose_name_plural': '需要',
            },
        ),
        migrations.AddField(
            model_name='f_item',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app.Tags', verbose_name='訳あり理由（PCではCtrlキーを押しながら複数選択可）'),
        ),
        migrations.AddField(
            model_name='f_item',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='F_UpdatedBy', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='f_item',
            name='vegetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Vegetable', verbose_name='野菜の種類'),
        ),
    ]
