# Generated by Django 3.0.6 on 2020-06-18 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 25, 23, 57, 13, 599540), null=True, verbose_name='出品期限'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='quontity',
            field=models.PositiveIntegerField(verbose_name='出品セット数'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='quontity_left',
            field=models.PositiveIntegerField(editable=False, verbose_name='在庫'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='quontity',
            field=models.PositiveIntegerField(verbose_name='購入数量'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, verbose_name='合計金額'),
        ),
    ]
