# Generated by Django 3.0.6 on 2020-06-22 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200622_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 29, 15, 37, 12, 486181), null=True, verbose_name='出品期限'),
        ),
    ]
