# Generated by Django 3.0.4 on 2020-06-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200613_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='合計金額'),
        ),
    ]
