# Generated by Django 3.0.7 on 2020-06-27 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200627_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 4, 20, 2, 55, 256217), null=True, verbose_name='購入期限'),
        ),
    ]
