# Generated by Django 3.0.6 on 2020-06-29 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200627_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 6, 13, 20, 42, 62986), null=True, verbose_name='購入期限'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='rank',
            field=models.IntegerField(choices=[(1, 'Aランク（一般流通品)'), (2, 'Bランク（販売用訳あり品）'), (3, 'Cランク（販売不適可品）'), (4, 'Dランク（可食品）')], verbose_name='ランク'),
        ),
    ]
