# Generated by Django 3.0.6 on 2020-06-18 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200618_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 26, 0, 17, 8, 600327), null=True, verbose_name='出品期限'),
        ),
    ]
