# Generated by Django 3.0.6 on 2020-06-26 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200622_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='f_item',
            name='rank',
            field=models.IntegerField(choices=[(1, 'Aランク'), (2, 'Bランク'), (3, 'Cランク'), (4, 'Dランク')], default=2, verbose_name='ランク'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 3, 22, 14, 44, 561786), null=True, verbose_name='出品期限'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='商品名'),
        ),
    ]
