# Generated by Django 3.0.4 on 2020-07-01 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200629_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 8, 11, 39, 46, 76325), null=True, verbose_name='購入期限'),
        ),
    ]
