# Generated by Django 3.0.4 on 2020-06-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reservation_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='f_item',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='価格'),
        ),
        migrations.AddField(
            model_name='f_item',
            name='quontity_left',
            field=models.IntegerField(blank=True, null=True, verbose_name='在庫'),
        ),
    ]
