# Generated by Django 3.0.4 on 2020-06-16 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20200616_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='quontity',
            field=models.IntegerField(blank=True, null=True, verbose_name='購入数量'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='subscriber',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Subscriber', to=settings.AUTH_USER_MODEL, verbose_name='購入者'),
        ),
    ]
