# Generated by Django 2.2.4 on 2020-07-01 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200701_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 8, 23, 47, 30, 396008), null=True, verbose_name='購入期限'),
        ),
    ]
