# Generated by Django 3.0.4 on 2020-06-18 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200619_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 26, 2, 35, 21, 430773), null=True, verbose_name='出品期限'),
        ),
    ]
