# Generated by Django 3.0.6 on 2020-07-01 16:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20200701_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='f_item',
            name='delete',
            field=models.BooleanField(default=False, editable=False, verbose_name='削除済み'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='delete',
            field=models.BooleanField(default=False, editable=False, verbose_name='削除済み'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 1, 4, 44, 678901), null=True, verbose_name='購入期限'),
        ),
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(editable=False, verbose_name='送信時間')),
                ('message', models.TextField(verbose_name='お問い合わせ内容')),
                ('person', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='contact_person', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'お問い合わせログ',
                'verbose_name_plural': 'お問い合わせログ',
            },
        ),
    ]
