# Generated by Django 3.0.6 on 2020-06-26 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200626_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 3, 22, 24, 32, 247946), null=True, verbose_name='出品期限'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='価格（￥）'),
        ),
    ]
