# Generated by Django 2.2.4 on 2020-07-01 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200701_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 8, 23, 56, 5, 437265), null=True, verbose_name='購入期限'),
        ),
    ]
