# Generated by Django 3.0.6 on 2020-06-26 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200626_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 3, 22, 35, 59, 41533), null=True, verbose_name='出品期限'),
        ),
    ]
