# Generated by Django 3.0.6 on 2020-06-20 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200619_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 27, 18, 51, 43, 155276), null=True, verbose_name='出品期限'),
        ),
    ]
