# Generated by Django 3.0.7 on 2020-06-29 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200629_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 6, 14, 43, 50, 355332), null=True, verbose_name='購入期限'),
        ),
    ]
