# Generated by Django 3.0.6 on 2020-07-01 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200702_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 1, 7, 16, 581070), null=True, verbose_name='購入期限'),
        ),
    ]
