# Generated by Django 3.0.6 on 2020-07-02 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200701_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 13, 38, 33, 167013), null=True, verbose_name='購入期限'),
        ),
    ]
