# Generated by Django 3.0.6 on 2020-06-26 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200626_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 3, 22, 40, 4, 20082), null=True, verbose_name='出品期限'),
        ),
    ]
