# Generated by Django 3.0.6 on 2020-06-20 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200620_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 27, 19, 30, 18, 201372), null=True, verbose_name='出品期限'),
        ),
    ]
