# Generated by Django 3.0.4 on 2020-06-20 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200620_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 28, 0, 27, 38, 243698), null=True, verbose_name='出品期限'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='f_items/', verbose_name='写真'),
        ),
    ]
