# Generated by Django 3.0.4 on 2020-06-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200616_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='photo',
            field=models.ImageField(default=None, upload_to='f_items/', verbose_name='写真'),
        ),
    ]
