# Generated by Django 3.0.6 on 2020-07-02 05:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200702_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 14, 0, 14, 22682), null=True, verbose_name='購入期限'),
        ),
        migrations.CreateModel(
            name='F_item_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, verbose_name='変更時間')),
                ('target', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='update', to='app.F_Item', verbose_name='編集したアイテム')),
            ],
            options={
                'verbose_name': '商品編集ログ',
                'verbose_name_plural': '商品編集ログ',
            },
        ),
    ]
