# Generated by Django 3.0.6 on 2020-06-21 04:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20200621_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='I_name',
            field=models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.PROTECT, related_name='F_exhibitor', to=settings.AUTH_USER_MODEL, verbose_name='出品者'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 28, 13, 5, 19, 280852), null=True, verbose_name='出品期限'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='quontity_left',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='在庫'),
        ),
    ]
