# Generated by Django 3.0.4 on 2020-06-10 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20191216_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='作成時間')),
                ('quontity', models.IntegerField(blank=True, null=True, verbose_name='予約数量')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('subscriber', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Subscriber', to=settings.AUTH_USER_MODEL, verbose_name='予約者')),
                ('target', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='F_Item', to='app.F_Item', verbose_name='商品アイテム')),
            ],
        ),
    ]
