# Generated by Django 3.0.6 on 2020-07-01 16:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20200702_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlog',
            name='message',
            field=models.TextField(verbose_name='お問い合わせ内容'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_person', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='timestamp',
            field=models.DateTimeField(verbose_name='送信時間'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 1, 26, 17, 99893), null=True, verbose_name='購入期限'),
        ),
    ]
