# Generated by Django 3.0.6 on 2020-06-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200621_1305'),
        ('app', '0009_auto_20200621_2011'),
    ]

    operations = [
    ]
