# Generated by Django 3.0.4 on 2020-06-21 18:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200621_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 29, 3, 26, 16, 702562), null=True, verbose_name='出品期限'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='f_items/', verbose_name='写真（任意）'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='価格（￥）'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='quontity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, '1セット以上の出品をしてください')], verbose_name='出品セット数'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='quontity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, '1セット以上の購入をしてください')], verbose_name='購入数量'),
        ),
    ]
