# Generated by Django 3.0.4 on 2020-06-21 19:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20200622_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='出品時間'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='F_CreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='出品者'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 29, 4, 30, 59, 335135), null=True, verbose_name='出品期限'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app.Tags', verbose_name='タグ（PCではCtrlキーを押しながら複数選択可）'),
        ),
    ]
