# Generated by Django 3.0.4 on 2020-06-21 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200622_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 29, 4, 34, 44, 36164), null=True, verbose_name='出品期限'),
        ),
    ]
