# Generated by Django 3.0.6 on 2020-07-01 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200702_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='f_item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='削除時間'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='削除時間'),
        ),
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 1, 46, 6, 434881), null=True, verbose_name='購入期限'),
        ),
    ]
