# Generated by Django 3.0.7 on 2020-07-02 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200702_0146'),
        ('app', '0008_auto_20200702_1400'),
        ('app', '0006_auto_20200629_1443'),
    ]

    operations = [
    ]
