# Generated by Django 3.0.7 on 2020-07-02 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20200702_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 19, 0, 29, 333345), null=True, verbose_name='購入期限'),
        ),
    ]
