# Generated by Django 3.0.7 on 2020-07-02 06:47

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_merge_20200702_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 15, 47, 36, 476296), null=True, verbose_name='購入期限'),
        ),
        migrations.CreateModel(
            name='F_Item_Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25, null=True, verbose_name='商品名')),
                ('unit_amount', models.CharField(max_length=10, verbose_name='１セット内容量')),
                ('rank', models.IntegerField(choices=[(1, 'Aランク（一般流通品)'), (2, 'Bランク（販売用訳あり品）'), (3, 'Cランク（販売不適可品）'), (4, 'Dランク（可食品）')], null=True, verbose_name='ランク')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('quontity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, '1セット以上の出品をしてください')], verbose_name='出品セット数')),
                ('quontity_left', models.PositiveIntegerField(blank=True, null=True, verbose_name='在庫')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='セット単価（￥）')),
                ('deadline', models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 15, 47, 36, 479295), null=True, verbose_name='購入期限')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='f_items/', verbose_name='写真（任意）')),
                ('delete', models.BooleanField(default=False, verbose_name='削除済み')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='出品時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='更新時間')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='削除時間')),
                ('I_name', models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.PROTECT, related_name='F_Edit', to=settings.AUTH_USER_MODEL, verbose_name='出品者')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='app.Tags', verbose_name='訳あり理由')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='F_EditedBy', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Vegetable', verbose_name='野菜の種類')),
            ],
        ),
    ]
