# Generated by Django 3.0.7 on 2020-07-02 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200702_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='f_item_edit',
            options={'verbose_name': '商品編集ログ', 'verbose_name_plural': '商品編集ログ'},
        ),
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 15, 52, 43, 903824), null=True, verbose_name='購入期限'),
        ),
        migrations.AlterField(
            model_name='f_item_edit',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 15, 52, 43, 905823), null=True, verbose_name='購入期限'),
        ),
        migrations.DeleteModel(
            name='F_item_update',
        ),
    ]
