# Generated by Django 3.0.6 on 2020-07-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200629_1443'),
        ('app', '0017_auto_20200702_1552'),
    ]

    operations = [
    ]
