# Generated by Django 3.0.7 on 2020-07-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200702_1900'),
        ('app', '0018_merge_20200702_1858'),
    ]

    operations = [
    ]
