# Generated by Django 3.0.7 on 2020-07-02 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_merge_20200703_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_item',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 10, 0, 31, 31, 481617), null=True, verbose_name='購入期限'),
        ),
        migrations.AlterField(
            model_name='f_item_edit',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 10, 0, 31, 31, 484666), null=True, verbose_name='購入期限'),
        ),
    ]
